name: jav_manager
description: 本地视频媒体管理器
publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  sqflite_common_ffi: ^2.3.1
  path_provider: ^2.0.15
  path: ^1.8.3
  http: ^1.1.0
  html: ^0.15.4
  xml: ^6.3.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  window_manager: ^0.3.7
  shared_preferences: ^2.2.2
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    image_path: "app_icon.png"
    icon_size: 256

flutter:
  uses-material-design: true

  fonts:
    - family: MapleMonoNL-NF-CN
      fonts:
        - asset: fonts/MapleMonoNL-NF-CN-Medium.ttf
